### ISSUE TITLE
Error in Build step 10 on Raspbian Stretch

### ISSUE THREAD

**Issue by Pibbers** [phev-remote/phevctl#1]
Step 10/12 : RUN mkdir -p build && cd build && cmake .. && make
 ---> Running in e62222329c13
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /src/phevctl/build
Scanning dependencies of target phevctl
[ 50%] Building C object CMakeFiles/phevctl.dir/main.c.o
/src/phevctl/main.c: In function 'main_eventHandler':
/src/phevctl/main.c:280:14: error: 'PHEV_START' undeclared (first use in this function); did you mean 'PHEV_STARTED'?
         case PHEV_START:
              ^~~~~~~~~~
              PHEV_STARTED
/src/phevctl/main.c:280:14: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/phevctl.dir/build.make:63: CMakeFiles/phevctl.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/phevctl.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c mkdir -p build && cd build && cmake .. && make' returned a non-zero code: 2

docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:32:16 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:26:16 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by papawattu** [comment]
Hi

This is down to a change I made recently to the core library, I'd not pushed the changes.  Should be fixed now.

Jamie.

**Comment by Pibbers** [comment]
Thanks.  Tried build again and set --no-cache to make sure picked up latest core repository but failed again with the same error

[ 50%] Building C object CMakeFiles/phevctl.dir/main.c.o
/src/phevctl/main.c: In function 'main_eventHandler':
/src/phevctl/main.c:280:14: error: 'PHEV_START' undeclared (first use in this function); did you mean 'PHEV_STARTED'?
         case PHEV_START:
              ^~~~~~~~~~
              PHEV_STARTED
/src/phevctl/main.c:280:14: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/phevctl.dir/build.make:63: CMakeFiles/phevctl.dir/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/phevctl.dir/all] Error 2
make: *** [Makefile:84: all] Error 2


Changed line 280 in main.c from PHEV_START to PHEV_STARTED and compiled correctly this time

**Comment by papawattu** [comment]
Fixed with latest push
